# Generated by Django 5.0.9 on 2024-09-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
