# Generated by Django 5.0.9 on 2024-09-08 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_product_alter_payment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_cents',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('square_api', 'Credit Card/Debit Card (Online)'), ('cash', 'In-Person Cash Payment'), ('other', 'Other Payment Method'), ('paypal', 'PayPal Payment (LEGACY - DO NOT USE FOR NEW PAYMENTS)'), ('venmo', 'Venmo Payment (LEGACY - DO NOT USE FOR NEW PAYMENTS)'), ('cashapp', 'Cash App Payment (LEGACY - DO NOT USE FOR NEW PAYMENTS)')], default='other'),
        ),
    ]
