# Generated by Django 5.0.9 on 2024-09-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_amount_cents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='max_purchases',
            new_name='max_purchases_per_user',
        ),
    ]
