# Generated by Django 5.1.2 on 2024-10-23 03:06

import computedfields.resolver
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_alter_payment_created_at_alter_payment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.product'),
        ),
        migrations.CreateModel(
            name='PurchasedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_products', to='payments.payment')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.product')),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
