# Generated by Django 5.1.2 on 2024-10-23 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_alter_payment_product_purchasedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.product'),
        ),
    ]
