# Generated by Django 5.1.2 on 2024-10-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_migrate_payment_products_to_purchased_product_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
    ]
