# Generated by Django 5.1.2 on 2024-11-10 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasedproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
