# Generated by Django 5.0.8 on 2024-08-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_attendance_event_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.CharField(default='https://cometrobotics.org', max_length=200),
        ),
    ]
