# Generated by Django 5.1.2 on 2024-10-23 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_combatevent_combateventregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_events', to='events.event'),
        ),
    ]
