# Generated by Django 5.1.2 on 2024-11-08 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_combatevent_event'),
        ('payments', '0023_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combatevent',
            name='documenso_adult_waiver_id',
        ),
        migrations.RemoveField(
            model_name='combatevent',
            name='documenso_minor_waiver_id',
        ),
        migrations.AlterField(
            model_name='combatevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combat_event', to='events.event'),
        ),
        migrations.CreateModel(
            name='CombatTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_combat_events_team_id', models.CharField()),
                ('name', models.CharField(max_length=200)),
                ('managers', models.ManyToManyField(related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CombatRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_combat_events_robot_id', models.CharField()),
                ('purchased_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.purchasedproduct')),
                ('combat_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.combatteam')),
            ],
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('internal_description', models.CharField(max_length=200)),
                ('minors_must_complete', models.BooleanField(default=False)),
                ('documenso_id', models.CharField(max_length=200)),
                ('alternate_for_waiver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.waiver')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('waiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.waiver')),
            ],
        ),
        migrations.DeleteModel(
            name='CombatEventRegistration',
        ),
    ]
