# Generated by Django 5.1.2 on 2024-11-08 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_combatevent_documenso_adult_waiver_id_and_more'),
        ('payments', '0023_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combatrobot',
            name='purchased_product',
        ),
        migrations.AddField(
            model_name='combatrobot',
            name='events',
            field=models.ManyToManyField(related_name='combat_robots', to='events.combatevent'),
        ),
        migrations.AddField(
            model_name='combatrobot',
            name='owners',
            field=models.ManyToManyField(related_name='combat_robots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='combatrobot',
            name='purchased_products',
            field=models.ManyToManyField(related_name='combat_robots', to='payments.purchasedproduct'),
        ),
    ]
