# Generated by Django 5.1.2 on 2024-11-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_combatrobot_purchased_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatrobot',
            name='name',
            field=models.CharField(default='Untitled Robot', max_length=200),
            preserve_default=False,
        ),
    ]
