# Generated by Django 5.1.2 on 2024-11-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_combatrobot_name'),
        ('payments', '0023_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatrobot',
            name='purchased_products',
            field=models.ManyToManyField(blank=True, related_name='combat_robots', to='payments.purchasedproduct'),
        ),
    ]
