# Generated by Django 5.1.2 on 2024-11-08 22:21

import common.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_combatrobot_purchased_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiver',
            old_name='minors_must_complete',
            new_name='is_alternate_waiver_for_minors',
        ),
        migrations.AddField(
            model_name='completedwaiver',
            name='documenso_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='completedwaiver',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedwaiver',
            name='is_signed',
            field=models.BooleanField(default=False, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedwaiver',
            name='signature_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_verifications', to=settings.AUTH_USER_MODEL, validators=[common.utils.validate_staff]),
        ),
        migrations.AddField(
            model_name='completedwaiver',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='completedwaiver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_statuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
