# Generated by Django 5.1.2 on 2024-11-08 22:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_rename_minors_must_complete_waiver_is_alternate_waiver_for_minors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedWaiver',
            new_name='WaiverStatus',
        ),
    ]
