# Generated by Django 5.1.2 on 2024-11-08 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_rename_completedwaiver_waiverstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiver',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='events.combatevent'),
        ),
    ]
