# Generated by Django 5.1.2 on 2024-11-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_waiver_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiver',
            old_name='event',
            new_name='combat_event',
        ),
    ]
