# Generated by Django 5.1.2 on 2024-11-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_combatevent_created_at_combatevent_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatrobot',
            name='weight_class',
            field=models.CharField(choices=[('plant', 'Plastic Ant (1lb)'), ('ant', 'Antweight (3lb)'), ('beetle', 'Beetleweight (1lb)')], default='ant'),
            preserve_default=False,
        ),
    ]
