# Generated by Django 5.1.2 on 2024-11-12 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_combatrobot_weight_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combatrobot',
            old_name='events',
            new_name='combat_events',
        ),
    ]
