# Generated by Django 5.1.2 on 2024-11-13 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_rename_events_combatrobot_combat_events'),
        ('payments', '0024_purchasedproduct_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='combatrobot',
            constraint=models.UniqueConstraint(condition=models.Q(('robot_combat_events_robot_id__isnull', False)), fields=('robot_combat_events_robot_id',), name='robot_combat_events_robot_id_unique_when_not_null'),
        ),
        migrations.AddConstraint(
            model_name='combatteam',
            constraint=models.UniqueConstraint(condition=models.Q(('robot_combat_events_team_id__isnull', False)), fields=('robot_combat_events_team_id',), name='robot_combat_events_team_id_unique_when_not_null'),
        ),
    ]
