# Generated by Django 5.1.2 on 2024-11-13 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_combatrobot_robot_combat_events_robot_id_unique_when_not_null_and_more'),
        ('payments', '0024_purchasedproduct_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='combatrobot',
            name='robot_combat_events_robot_id_unique_when_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='combatteam',
            name='robot_combat_events_team_id_unique_when_not_null',
        ),
        migrations.AddConstraint(
            model_name='combatrobot',
            constraint=models.UniqueConstraint(fields=('robot_combat_events_robot_id',), name='robot_combat_events_robot_id_unique_nulls_not_distinct', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='combatteam',
            constraint=models.UniqueConstraint(fields=('robot_combat_events_team_id',), name='robot_combat_events_team_id_unique_nulls_not_distinct', nulls_distinct=False),
        ),
    ]
