# Generated by Django 5.1.2 on 2024-11-13 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_remove_combatrobot_robot_combat_events_robot_id_unique_when_not_null_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatEventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('competing', 'Competing'), ('on_waitlist', 'On Waitlist')], default='competing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combat_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_event_registrations', to='events.combatevent')),
                ('combat_robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_event_registrations', to='events.combatrobot')),
            ],
        ),
        migrations.RemoveField(
            model_name='combatrobot',
            name='combat_events',
        ),
        migrations.AddField(
            model_name='combatrobot',
            name='combat_events',
            field=models.ManyToManyField(related_name='combat_robots', through='events.CombatEventRegistration', to='events.combatevent'),
        ),
    ]
