# Generated by Django 5.1.2 on 2024-11-15 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_combateventregistration_combat_event_registrations_combat_event_combat_robot_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatrobot',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='alternate_for_waiver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternate_waivers', to='events.waiver'),
        ),
    ]
