# Generated by Django 5.1.6 on 2025-03-06 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_event_project_event_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combatrobot',
            name='combat_events',
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='combat_event',
        ),
        migrations.RemoveField(
            model_name='combateventregistration',
            name='combat_event',
        ),
        migrations.RemoveField(
            model_name='combateventregistration',
            name='combat_robot',
        ),
        migrations.RemoveField(
            model_name='combatrobot',
            name='combat_team',
        ),
        migrations.RemoveField(
            model_name='combatrobot',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='combatrobot',
            name='purchased_products',
        ),
        migrations.RemoveField(
            model_name='combatteam',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='alternate_for_waiver_id',
        ),
        migrations.RemoveField(
            model_name='waiverstatus',
            name='waiver',
        ),
        migrations.RemoveField(
            model_name='waiverstatus',
            name='signature_verified_by',
        ),
        migrations.RemoveField(
            model_name='waiverstatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='CombatEvent',
        ),
        migrations.DeleteModel(
            name='CombatEventRegistration',
        ),
        migrations.DeleteModel(
            name='CombatRobot',
        ),
        migrations.DeleteModel(
            name='CombatTeam',
        ),
        migrations.DeleteModel(
            name='Waiver',
        ),
        migrations.DeleteModel(
            name='WaiverStatus',
        ),
    ]
