# Generated by Django 5.1.7 on 2025-08-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_remove_combatrobot_combat_events_and_more'),
        ('core', '0025_copy_student_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserIdentification',
        ),
    ]
