# Generated by Django 5.1.15 on 2026-09-22 15:45

from django.db import migrations, models


def backfill_checkin_method(apps, schema_editor):
    Attendance = apps.get_model('events', 'Attendance')
    Attendance.objects.all().update(checkin_method='staff_initiated')


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_delete_useridentification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkin_method',
            field=models.CharField(choices=[('self_qr', 'Self Check-in via QR Code'), ('staff_initiated', 'Staff Initiated Check-in')], default='staff_initiated', max_length=20),
        ),
        migrations.RunPython(backfill_checkin_method, reverse_code=migrations.RunPython.noop),
    ]
