# Generated by Django 5.1.15 on 2026-09-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_add_checkin_method_to_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='checkin_method',
        ),
        migrations.AddField(
            model_name='attendance',
            name='sign_in_method',
            field=models.CharField(choices=[('self_qr', 'Self Sign-In via QR Code'), ('staff_initiated', 'Staff Initiated Sign-In')], db_column='checkin_method', default='staff_initiated', max_length=20),
        ),
    ]
