# Generated by Django 5.1.15 on 2026-09-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_remove_attendance_checkin_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sign_in_method',
            field=models.CharField(choices=[('self_qr', 'Self Sign-In via QR Code'), ('staff_initiated', 'Staff Initiated Sign-In')], default='staff_initiated', max_length=20),
        ),
    ]
