# Generated by Django 5.1.6 on 2025-02-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='default_team',
        ),
    ]
