# Generated by Django 5.1.6 on 2025-02-18 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_team_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leads',
            field=models.ManyToManyField(related_name='teams_leading', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(related_name='projects_managing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
