# Generated by Django 5.1.6 on 2025-02-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_team_leads_team_members_alter_project_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='emoji',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
