# Generated by Django 5.1.1 on 2024-09-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_discord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='discord_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
