# Generated by Django 5.1.1 on 2024-10-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_utd_affiliate',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
