# Generated by Django 5.1.2 on 2024-10-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_utd_affiliate',
            field=models.BooleanField(default=True),
        ),
    ]
