# Generated by Django 5.1.4 on 2025-02-15 05:44

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_diet_userprofile_is_hispanic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='diet',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'Shellfish Allergy'), ('N', 'Nut Allergy'), ('VT', 'Vegetarian'), ('VN', 'Vegan'), ('P', 'Pescatarian'), ('H', 'Halal'), ('K', 'Kosher'), ('L', 'Lactose Intolerant'), ('G', 'Gluten Free')], max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='race',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('W', 'White'), ('B', 'Black or African American'), ('A', 'Asian'), ('N', 'American Indian or Alaska Native'), ('P', 'Native Hawaiian or Other Pacific Islander')], max_length=9, null=True),
        ),
    ]
