# Generated by Django 5.1.6 on 2025-02-16 04:11

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_userprofile_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('organization_name', models.CharField(default='Your Organization')),
                ('accent_color_hex', colorfield.fields.ColorField(default='#4BC0FF', image_field=None, max_length=25, samples=None)),
            ],
        ),
    ]
