# Generated by Django 5.1.6 on 2025-02-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_serversettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversettings',
            name='photo',
            field=models.ImageField(default=1, upload_to='logos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown')], default=None, null=True),
        ),
    ]
