# Generated by Django 5.1.7 on 2025-03-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_userprofile_is_lgbt_alter_userprofile_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='race',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='race',
            field=models.ManyToManyField(to='core.race'),
        ),
    ]
