# Generated by Django 5.1.7 on 2025-03-09 04:59

from django.db import migrations

def create_races(apps, schema_editor):
    Race = apps.get_model("core", "Race")
    Race.objects.create(name='Black or African American')
    Race.objects.create(name='White')
    Race.objects.create(name='East Asian')
    Race.objects.create(name='South Asian')
    Race.objects.create(name='American Indian or Alaska Native')
    Race.objects.create(name='Native Hawaiian or Other Pacific Islander')
    Race.objects.create(name='Middle Eastern')
    Race.objects.create(name='Other')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_race_remove_userprofile_race_userprofile_race'),
    ]

    operations = [
        migrations.RunPython(create_races),
    ]
