# Generated by Django 5.1.7 on 2025-08-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20250308_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='serversettings',
            options={'verbose_name': 'server configuration', 'verbose_name_plural': 'server configurations'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='diet',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diet',
            field=models.ManyToManyField(blank=True, to='core.diet'),
        ),
    ]
