# Generated by Django 5.1.7 on 2025-08-24 06:48

from django.db import migrations


def seed_dietary_restrictions(apps, schema_editor):
    """Seed the Diet model with the dietary restrictions that were previously defined as choices."""
    Diet = apps.get_model('core', 'Diet')
    
    dietary_restrictions = [
        "Shellfish Allergy",
        "Nut Allergy", 
        "Vegetarian",
        "Vegan",
        "Pescatarian",
        "Halal",
        "Kosher",
        "Lactose Intolerant",
        "Gluten Free",
    ]
    
    # Create Diet objects for each restriction
    for restriction in dietary_restrictions:
        Diet.objects.get_or_create(name=restriction)


def reverse_seed_dietary_restrictions(apps, schema_editor):
    """Remove all dietary restrictions."""
    Diet = apps.get_model('core', 'Diet')
    Diet.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_diet_alter_serversettings_options_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_dietary_restrictions, reverse_seed_dietary_restrictions),
    ]
