# Generated by Django 5.1.7 on 2025-08-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_seed_dietary_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comet_card_serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='race',
            field=models.ManyToManyField(blank=True, to='core.race'),
        ),
    ]
