# Generated by Django 5.1.12 on 2025-10-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_copy_student_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown')], default=None, null=True),
        ),
    ]
