# Generated by Django 5.1.12 on 2025-10-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
      ('core', '0026_alter_userprofile_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversettings',
            name='initial_setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
