# Generated by Django 5.1.15 on 2026-09-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_userprofile_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Address members should reach out to with questions. Used as the Reply-To on transactional emails and shown in their footer. Leave blank to omit it.', max_length=254),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='mailing_address',
            field=models.TextField(blank=True, help_text='Physical mailing address shown in the footer of transactional emails. Spam filters treat a missing postal address as a signal that mail is not from a real organization, so setting this improves deliverability. Leave blank to omit it.'),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='website_url',
            field=models.URLField(blank=True, help_text='Public website linked from the footer of transactional emails. Leave blank to omit it.'),
        ),
    ]
