# Generated by Django 5.0.6 on 2024-06-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='destination_url',
            field=models.URLField(default='/'),
        ),
    ]
