# Generated by Django 5.1.1 on 2024-09-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlinks',
            name='link_type',
            field=models.CharField(choices=[('discord', 'Discord'), ('other', 'Other')], max_length=200),
        ),
    ]
