# Generated by Django 5.1.1 on 2024-09-10 07:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountlinks_link_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountLinks',
            new_name='AccountLink',
        ),
    ]
