# Generated by Django 5.1.1 on 2024-09-10 07:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accountlinks_accountlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountlink',
            name='id',
        ),
        migrations.AlterField(
            model_name='accountlink',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
