# Generated by Django 5.1.1 on 2024-09-10 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_accountlink_id_alter_accountlink_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlink',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
