# Generated by Django 5.1.1 on 2024-09-12 02:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountlink_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlink',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
