# Generated by Django 5.1.15 on 2026-09-05 09:13

import accounts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_accountlink_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStub",
            fields=[
                (
                    "user_registration_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
                ),
                ("net_id", models.CharField(max_length=150, unique=True)),
                ("pending_discord_id", models.CharField(blank=True, max_length=200, null=True, unique=True)),
                (
                    "after_registration_redirect_destination",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[accounts.models.validate_after_registration_redirect_destination],
                    ),
                ),
                ("expires_at", models.DateTimeField(default=accounts.models.get_registration_expiration)),
            ],
        ),
    ]
