# Generated by Django 5.1.15 on 2026-09-05 09:13

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accountlink_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStub',
            fields=[
                ('user_registration_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('after_registration_redirect_destination', models.TextField(validators=[accounts.models.validate_after_registration_redirect_destination])),
                ('expires_at', models.DateTimeField(default=accounts.models.get_registration_expiration)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
