# Generated by Django 5.1.15 on 2026-09-05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_userstub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstub",
            name="after_registration_redirect_destination",
            field=models.TextField(blank=True, null=True, validators=[accounts.models.validate_after_registration_redirect_destination]),
        ),
    ]
