/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const StoreLazyImport = createFileRoute('/store')()
const RoboteventLazyImport = createFileRoute('/robot_event')()
const LoginLazyImport = createFileRoute('/login')()
const CheckoutLazyImport = createFileRoute('/checkout')()
const AuthLazyImport = createFileRoute('/auth')()

// Create/Update Routes

const StoreLazyRoute = StoreLazyImport.update({
  path: '/store',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/store.lazy').then((d) => d.Route))

const RoboteventLazyRoute = RoboteventLazyImport.update({
  path: '/robot_event',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/robot_event.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const CheckoutLazyRoute = CheckoutLazyImport.update({
  path: '/checkout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/checkout.lazy').then((d) => d.Route))

const AuthLazyRoute = AuthLazyImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLazyImport
      parentRoute: typeof rootRoute
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/robot_event': {
      id: '/robot_event'
      path: '/robot_event'
      fullPath: '/robot_event'
      preLoaderRoute: typeof RoboteventLazyImport
      parentRoute: typeof rootRoute
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/auth': typeof AuthLazyRoute
  '/checkout': typeof CheckoutLazyRoute
  '/login': typeof LoginLazyRoute
  '/robot_event': typeof RoboteventLazyRoute
  '/store': typeof StoreLazyRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthLazyRoute
  '/checkout': typeof CheckoutLazyRoute
  '/login': typeof LoginLazyRoute
  '/robot_event': typeof RoboteventLazyRoute
  '/store': typeof StoreLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/auth': typeof AuthLazyRoute
  '/checkout': typeof CheckoutLazyRoute
  '/login': typeof LoginLazyRoute
  '/robot_event': typeof RoboteventLazyRoute
  '/store': typeof StoreLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth' | '/checkout' | '/login' | '/robot_event' | '/store'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/checkout' | '/login' | '/robot_event' | '/store'
  id: '__root__' | '/auth' | '/checkout' | '/login' | '/robot_event' | '/store'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthLazyRoute: typeof AuthLazyRoute
  CheckoutLazyRoute: typeof CheckoutLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  RoboteventLazyRoute: typeof RoboteventLazyRoute
  StoreLazyRoute: typeof StoreLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthLazyRoute: AuthLazyRoute,
  CheckoutLazyRoute: CheckoutLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  RoboteventLazyRoute: RoboteventLazyRoute,
  StoreLazyRoute: StoreLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/auth",
        "/checkout",
        "/login",
        "/robot_event",
        "/store"
      ]
    },
    "/auth": {
      "filePath": "auth.lazy.tsx"
    },
    "/checkout": {
      "filePath": "checkout.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/robot_event": {
      "filePath": "robot_event.lazy.tsx"
    },
    "/store": {
      "filePath": "store.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
