on:
  push:
    branches: [ main ]
    
jobs:
  deploy-prod:
    runs-on: self-hosted
    steps:
      - working-directory: /root/clubManager
      - run: pwd
      - run: git pull
      - run: ./deploy/run.sh
    
    
