on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    runs-on: self-hosted
    steps:
      - name: Check current directory
        run: pwd
        working-directory: /root/clubManager

      - name: Pull latest changes
        run: git pull
        working-directory: /root/clubManager

      - name: Run deployment script
        run: ./deploy/run.sh
        working-directory: /root/clubManager
